name: video_player_macos
description: A new Flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.1"

dependencies:
  flutter:
    sdk: flutter
  video_player_avfoundation: ^2.4.6
  video_player_platform_interface: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  pigeon: ^9.2.4

flutter:
  plugin:
    platforms:
      macos:
        dartPluginClass: AVFoundationVideoPlayer
        pluginClass: VideoPlayerPlugin
